### PR TITLE
Remove *.so and *.o from src directory

### PR DESCRIPTION
**Pull request by agrueneberg**
Hi Lian,

@sudhaveturi had a problem installing the package on the cluster. If *.so and *.o files are present in the src directory, they will not be recompiled when installing the package. This will create problems on systems that use a different compiler than your own, for example on the cluster running Linux.

I have removed the files and also added a .gitignore file so that you don't check them in by accident anymore.

Hope you're having a good time in IA,
Alex

### CODE REVIEW

**Comment by lian0090** [comment]
@agrueneberg @sudhaveturi Thanks Alex! Is there anyway to move this repository under your name or under QuantGen? I probably cannot respond to issues during day time. Maybe it is easier managed by Sudha or you for small changes.

**Comment by agrueneberg** [comment]
Sure, I forked it over to QuantGen and gave you admin rights. That way you will be kept in the loop.

**Comment by lian0090** [comment]
Thanks Alex!!!

Do you know how I can push to this branch? I used to push to my own repository like this: git push origin master.

What should I do with this one?

Thank you ^_^

Lian

**Comment by agrueneberg** [comment]
The `origin` in `git push origin master` maps to your repository. You could add another name such as `quantgen` with `git remote add quantgen git@github.com:QuantGen/BGData.git` for SSH or `git remote add quantgen https://github.com/QuantGen/BGData.git` for HTTPS (not sure which one you're using) and then push with `git push quantgen master`. Alternatively, you could replace origin if you don't intend to push to your own repository anymore: `git remote set-url origin git@github.com:QuantGen/BGData.git` for SSH or `git remote set-url origin https://github.com/QuantGen/BGData.git` for HTTPS.

**Comment by lian0090** [comment]
Thanks Alex! That works well~~

Lian

**Pull request merged**
